# Generated by Django 4.1 on 2024-05-13 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='User has not provided any title', max_length=200)),
                ('supervisor', models.CharField(default='User has not provided any supervisor', max_length=200)),
                ('category', models.CharField(default='User has not provided any category', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisDescription',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='thesis_site.thesis')),
                ('description', models.TextField(default='User has not provided any description')),
            ],
        ),
    ]
