# Generated by Django 4.1 on 2024-04-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('supervisor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesis_site.thesis')),
            ],
        ),
    ]
